### ISSUE TITLE
Revisión del Código (HTML + CSS con Flexbox)

### ISSUE THREAD

**Issue by papercri** [meritxell98/S1.1.-HTML-i-CSS-amb-Flex#1]
# Revisión del Código

## Errores en el README  
- Hay errores de ortografía en los nombres de archivo: `indext.html` y `stule.css`.  
  Asegúrate de corregirlos a `index.html` y `style.css`.  
- Te recomiendo hacer el README más descriptivo.  
  Agregar imágenes y explicaciones paso a paso ayudaría a comprender mejor el ejercicio.  

---

## Estructura y semántica
- `<p>` no es la mejor opción para `.logo`, `.nav` y `.social`. Mejor usar `<div>` o `<span>`.  
- `<section>` no tiene `class` o `id`, lo cual podría mejorar su identificación en CSS.  
- `<div class="aside">` es innecesario, ya que `<aside>` ya cumple esa función.  

---

## Maquetación  

En lugar de agregar `max-width` al `<body>`, usa un `<div class="container">` dentro del `<body>`.  
Luego aplica:  

  ```css
  .container {
      max-width: 1200px;
      margin: 0 auto;
  }

  ```

**Uso de `margin` y `padding`**
   - En varias partes se repiten valores como:  
     ```css
     margin: 20px 20px 20px 20px;
     ```
     Se puede simplificar a:
     ```css
     margin: 20px;
     ```

**Distribución en `nav`**
   - `.nav2 { flex: 2; }` hace que la barra de navegación se vea desbalanceada.  
     Mejor usar:
     ```css
     nav {
         display: flex;
         justify-content: space-between;
     }
     ```

**Efecto `hover` en `.nav1`**
   - El `transform: scale(1.2);` puede afectar el diseño.  
     Mejor hacerlo más fluido:
     ```css
     .nav1:hover {
         background-color: pink;
         transform: scale(1.2);
         transition: transform 0.3s ease;
     }
     ```

**Mejoras en responsive (`@media`)**
   - En los `@media`, `.inside-article { flex-direction: column; }` puede acumular demasiados márgenes.  
     Se recomienda agregar `gap` en su lugar:
     ```css
     .inside-article {
         display: flex;
         flex-direction: column;
         gap: 10px;
     }
     ```

### **Versión tablet**

- En la version tablet los article de la session azul deberían estar en 2 columnas.

- Te recomiendo que el breakpoint para tablet sea de 768px en vez que 900px

### **Versión Desktop**

 La sección de **publicidad** no se muestra como en el diseño.  
   - Para corregirlo, elimina `<div class="aside">` y deja solo `<aside>`.  
   - Configura correctamente el contenedor y cambia `<div class="article">` a `<article>`.  
   - Agrega `flex-grow: 1` a `<article>` para un mejor ajuste:  

   ```css
   article {
       flex-grow: 1;
   }
